import { AuthenticationProvider } from "@/contexts/authenticationContext";
import { AuthorizationProvider } from "@/contexts/authorizationContext";
import AppTheme from "@/packages/common/theme/mui";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SWRConfig } from "swr";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <AuthenticationProvider>
          <AuthorizationProvider>
            <LocalizationProvider dateAdapter={AdapterDayjs}>
              <SWRConfig>
                <AppTheme>{children}</AppTheme>
              </SWRConfig>
            </LocalizationProvider>
          </AuthorizationProvider>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
