export const fontFamilyValues = [
  "Arial",
  "Bahnschrift",
  "Calibri",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",
  "Ebrima",
  "Franklin Gothic",
  "Gabriola",
  "Gadugi",
  "Georgia",
  "Inter",
  "Impact",
  "Ink Free",
  "Javanese Text",
  "Leelawadee UI",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Malgun Gothic",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei UI",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft YaHei",
  "Microsoft YaHei UI",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "PMingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "Mongolian Baiti",
  "MS Gothic",
  "MS UI Gothic",
  "MS PGothic",
  "MV Boli",
  "Myanmar Text",
  "Nirmala UI",
  "Palatino Linotype",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Symbol",
  "SimSun",
  "NSimSun",
  "SimSun-ExtB",
  "Sitka Small",
  "Sitka Text",
  "Sitka Subheading",
  "Sitka Heading",
  "Sitka Display",
  "Sitka Banner",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
  "Webdings",
  "Wingdings",
  "Yu Gothic",
  "Yu Gothic UI",
  "HoloLens MDL2 Assets",
  "Marlett",
];
